id: P9A8A491A
initial_creation_type: input
source_metadata:
  title: Nyangral Nyima Özer Series
  language: en
  description: 'Texts composed or revealed by the important tertön Nyangral Nyima
    Özer (nyang ral nyi ma ''od zer, 1124–1192):'
  volume:
    816844b229e244e99f36ae99888c0788:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    6dc95610edd441bf9deffd4b24098a46:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Prayers to Guru Rinpoche
    833b7500d69c455d9e328f46ae5e5034:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Prayers to Guru Rinpoche
created_at: '2022-03-01T01:04:34.418768'
last_modified_at: '2022-03-01T01:04:34.418775'
